title: slic-reveng
description: Reverse-engineering subject-level neuroimaging data from meta-analyses
baseurl: "" # leave this blank for root
url: "https://slic-lab.github.io/slic-reveng/" # change to your GitHub Pages URL

remote_theme: "mmistakes/minimal-mistakes@4.24.0" # check GitHub for latest release

plugins:
  - jekyll-include-cache

# Optional extras
markdown: kramdown
theme: null