# site settings
title: slic-reveng
subtitle: ' &nbsp; | &nbsp; documentation'
email: sara.lariviere@usherbrooke.ca
description: ''
baseurl: "/slic-reveng" 
url: "https://slic-lab.github.io"  # the base hostname & protocol for your site
author: Sara Larivière
street_address: 3001, 12e Avenue Nord
city: Sherbrooke
state: QC
zip_code: J1H 5N4
country: Canada
# phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/slic-lab
  GitLab:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/saratheriver/
  Twitter: https://twitter.com/saratheriver
  Facebook: https://www.facebook.com/CRCHUS
  Slack:
  Youtube: https://www.youtube.com/@new-epilepsy
  Google-Scholar: https://scholar.google.ca/citations?user=Fet1xBYAAAAJ&hl=en

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md 
  - vendor
  - Gemfile
  - Gemfile.lock
  